# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=254, unique=True)),
                ('OCCUPATION', models.CharField(max_length=254)),
                ('IS_US_CITIZEN', models.BooleanField()),
            ],
        ),
    ]
