# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
